services:
  redis:
    image: redis:7.2.0
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sergioruy
      MONGO_INITDB_ROOT_PASSWORD: sergioruy
      MONGO_INITDB_DATABASE: pix
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
  zookeeper:
    image: docker.io/bitnami/zookeeper:3
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
     image: docker.io/bitnami/kafka:2
     ports:
       - "9092:9092"
     volumes:
       - "kafka_data:/bitnami"
     environment:
       - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
       - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
       - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
       - KAFKA_CREATE_TOPICS=pix_transaction:1:1, pix_transaction_revert:1:1
       - ALLOW_PLAINTEXT_LISTENER=yes
     depends_on:
       - zookeeper

volumes:
   mongodbdata:
     driver: local
   zookeeper_data:
     driver: local
   kafka_data:
     driver: local
