services:
  redis:
    image: redis:7.2.0
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sergioruy
      MONGO_INITDB_ROOT_PASSWORD: sergioruy
      MONGO_INITDB_DATABASE: pix
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
    driver: local
